### ISSUE TITLE
Consider transferring the repository to Tarantool organization

### ISSUE THREAD

**Issue by rybakit** [Sulverus/tarantool-docker#3]
Ref: https://github.com/tarantool/

Or even better transfer it to https://github.com/docker-library/official-images/tree/master/library.

**Comment by kostja** [comment]
Hi, I forked this repo to http://github.com/tarantool/tarantool-docker.
Transfer is more complicated, so let's just move over to tarantool org.

**Comment by rybakit** [comment]
Cool! For the record, the source repository needs to be updated as well: https://hub.docker.com/r/tarantool/tarantool/

**Comment by Sulverus** [comment]
Updated in tarantool docker-hub
https://hub.docker.com/r/tarantool/tarantool-docker/

**Comment by rybakit** [comment]
@Sulverus Is it possible to keep the old `tarantool/tarantool` name in the hub?
